name: Tests
on: [push]
jobs:
  api:
    runs-on: ubuntu-latest
    env:
      working_directory: ./services/api
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: yarn install
        working-directory: ${{ env.working_directory }}

      - name: Run Tests
        run: yarn test --silent
        working-directory: ${{ env.working_directory }}
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
        working-directory: ${{ env.working_directory }}
